---
version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - noinlineerr
    - ireturn
    - varnamelen
    - wsl
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
